### ISSUE TITLE
Easier way to add event handlers to a `smart-link`

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/vue-routing-anchor-parser#20]
Currently it's hard to add event handlers to a `smart-link`.  For example, a click handler needs to be bound as `@click.native` or `@click` depending on whether the `smart-link` gets rendered as a `nuxt-link` or a `span` / `a`.   

These events would be most useful:

* click
* mouseenter  /  mouseleave
* mousedown  /  mouseup
* focusin / focusout
* focus / blur

**Comment by weotch** [comment]
A fix for this has been released as v1.13.0
